// script of Facts.html (made by Rowan)
const facts = [
    " Ducks belong to the family Anatidae, which also includes swans and geese.",
    " There are over 120 different species of ducks.",
    " Ducks are found on every continent except Antarctica.",
    " A duck’s quack does echo, despite the myth that it doesn’t.",
    " Male ducks are called drakes, females are called hens, and ducklings are the young.",
    " Ducks have webbed feet which make them excellent swimmers.",
    " They can sleep with one eye open, thanks to a mechanism called unihemispheric slow-wave sleep.",
    " Ducks have waterproof feathers due to a special oil gland located near their tail.",
    " Some ducks migrate long distances, traveling thousands of miles between breeding and wintering grounds.",
    " Ducks have a specialized bill for filtering food from the water, called a lamellae.",
    " The largest species of duck is the Muscovy duck, which can weigh up to 15 pounds.",
    " Ducks can live for up to 10-15 years in the wild, depending on the species.",
    " Their diet varies widely depending on the species and can include plants, insects, and small fish.",
    " The mallard duck is one of the most common and recognizable species worldwide.",
    " Male ducks often have brighter and more colorful plumage compared to females.",
    " Ducks have excellent vision and can see a broader spectrum of colors than humans.",
    " Some species of ducks, like the northern pintail, can dive underwater to find food.",
    " The quack of a duck can be heard up to a mile away.",
    " Ducks are omnivores, meaning they eat both plants and animals.",
    " The longest migration of any duck species is undertaken by the northern pintail, which can travel up to 8,000 miles.",
    " Some ducks, like the wood duck, nest in trees rather than on the ground.",
    " Ducks are known to form monogamous pairs for the breeding season.",
    " The smallest duck species is the green-winged teal, which is about 12 inches long.",
    " Ducks have been domesticated for thousands of years and are raised for meat, eggs, and feathers.",
    " Some ducks can be found in urban environments and have adapted to living in city parks and ponds.",
    " Ducks have a unique way of communicating with each other using a variety of vocalizations.",
    " The average duck can consume up to 3,000 seeds per day while foraging.",
    " Female ducks often have more cryptic plumage to help them blend in with their surroundings while nesting.",
    " Ducks have a specialized muscle that helps them retract their head and neck while swimming.",
    " The mandarin duck is known for its striking and colorful plumage.",
    " Ducks are important for maintaining healthy aquatic ecosystems by controlling insect populations.",
    " They use their bills to 'dabble' for food on the water’s surface or to 'dive' for food underwater.",
    " The Muscovy duck is native to Central and South America but has been introduced to many other regions.",
    " Some ducks, like the canvasback, have a distinctive sloping profile on their heads.",
    " Ducks can adapt to various types of freshwater, saltwater, and brackish water habitats.",
    " They have been depicted in art and culture for centuries, from ancient Egyptian hieroglyphs to modern cartoons.",
    " The common eider is known for its soft and insulating down feathers.",
    " Ducks have a gland near their eyes called the nictitating membrane, which helps keep their eyes moist.",
    " The American black duck is often mistaken for a mallard due to its similar appearance.",
    " Ducks use a range of body language and posturing to communicate with each other.",
    " Some ducks, like the teal, are known for their rapid and agile flight.",
    " Ducks have been featured in many popular children’s stories and cartoons.",
    " The common merganser is a type of duck known for its sharp, serrated bill, which helps it catch fish.",
    " Ducks can regulate their body temperature by changing their blood flow and adjusting their feathers.",
    " Some species of ducks are known to form large flocks, called flocks, during migration.",
    " The wood duck is notable for its striking colors and ornate markings.",
    " Ducks have been kept as pets and for ornamental purposes for centuries.",
    " The tufted duck has a distinctive crest of feathers on its head.",
    " Ducks have specialized muscles in their legs and feet that help them navigate through water.",
    " The ring-necked duck is named for the ring of color around its neck.",
    " Ducks are highly social animals and often form large groups when feeding or resting.",
    " They can make a range of sounds, from quacking to whistling, depending on the species.",
    " Some ducks, like the eider, are known for their migratory patterns that follow seasonal changes.",
    " Ducks have a high metabolic rate and need to consume large amounts of food daily.",
    " The redhead duck has a distinctive red head and neck, which is a key identification feature.",
    " Ducks can walk, swim, and fly, making them highly adaptable to different environments.",
    " The gadwall is a species of duck known for its subtle and understated plumage.",
    " Ducks are often seen dabbling on the surface of water to find food.",
    " The lesser scaup is a diving duck known for its distinctive white body and dark head.",
    " Some ducks, like the northern shoveler, have large, spatula-shaped bills for filtering food.",
    " Ducks are known to engage in playful behaviors, such as splashing and chasing each other.",
    " The green-winged teal is one of the smallest and most colorful ducks.",
    " Ducks have specialized feathers that help them stay buoyant in water.",
    " The common goldeneye is known for its distinctive golden-yellow eye and black-and-white plumage.",
    " Ducks have a keen sense of hearing, which helps them detect predators and locate mates.",
    " Some ducks, like the black scoter, are known for their distinctive calls and vocalizations.",
    " Ducks have been used in traditional medicine in various cultures around the world.",
    " The American coot is a type of duck that is often mistaken for a chicken due to its similar appearance.",
    " Ducks are known to build nests in a variety of locations, including on the ground, in trees, and in reeds.",
    " The whistling duck gets its name from its distinctive whistling call.",
    " Ducks have been featured in various forms of popular media, including books, films, and television shows.",
    " The bufflehead is a small diving duck known for its striking black-and-white plumage and iridescent head.",
    " Ducks can often be seen engaging in a behavior called preening, where they use their beaks to clean and arrange their feathers.",
    " The long-tailed duck is known for its distinctive long tail feathers and striking plumage.",
    " Ducks have a special gland located near their tail called the uropygial gland that produces oils to waterproof their feathers.",
    " The common teal is a small duck known for its colorful plumage and distinctive call.",
    " Ducks are important for maintaining the balance of aquatic ecosystems by controlling insect and plant populations.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a unique way of communicating with their young, using a range of vocalizations and body language.",
    " Some species of ducks, like the hooded merganser, have distinctive crests of feathers on their heads.",
    " The red-breasted merganser is a diving duck known for its sharp bill and distinctive red breast.",
    " Ducks have a special adaptation in their digestive system that allows them to process a wide variety of foods.",
    " The goldeneye duck is known for its distinctive golden-yellow eye and striking plumage.",
    " Ducks have been studied extensively in scientific research, including studies on their migratory patterns and behavior.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have been used as a symbol of various cultures and religions throughout history.",
    " The wood duck is known for its striking colors and ornate markings, making it a popular subject for birdwatchers and photographers.",
    " Ducks have a wide range of vocalizations that they use to communicate with each other, including quacking, whistling, and grunting.",
    " Some ducks, like the mallard, have been domesticated and are kept as pets in many households.",
    " The lesser scaup is known for its distinctive black head and white body, making it easy to identify in the field.",
    " Ducks have a unique way of foraging for food, using their bills to filter out small organisms and plants from the water.",
    " The northern pintail is known for its elegant and slender neck, which gives it a distinctive appearance.",
    " Ducks have been featured in various forms of art and literature throughout history, including paintings, poems, and stories.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which gives it a unique appearance.",
    " Ducks have a specialized muscle in their legs that allows them to swim efficiently and with great speed.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks have a unique way of navigating through water, using their webbed feet and streamlined bodies to move quickly and efficiently.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill, which make it easy to identify in the field.",
    " Ducks are highly social animals and often form large flocks when feeding or migrating.",
    " Ducks have a special adaptation in their bills called lamellae, which are comb-like structures that help them filter out small food particles from the water.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation.",
    " The green-winged teal is one of the fastest flying ducks, reaching speeds of up to 40 mph.",
    " Ducks have a specialized bill structure called lamellae that helps them filter out small food particles from the water.",
    " The black-bellied whistling duck is known for its distinctive whistling call and striking black belly.",
    " Ducks have a special gland near their tail, called the uropygial gland, which secretes oil to help keep their feathers waterproof.",
    " The common merganser is an excellent fisherman, using its serrated bill to catch and hold slippery fish.",
    " Ducks have been featured in various cultural celebrations and folklore around the world.",
    " The redhead duck is known for its distinctive red head and neck, making it easy to spot in the wild.",
    " Some species of ducks, like the teal, are highly migratory and travel long distances between their breeding and wintering grounds.",
    " Ducks use a combination of vocalizations and body language to communicate with each other, especially during mating and feeding.",
    " The wood duck is unique among ducks for its ability to perch in trees thanks to its strong claws and agile feet.",
    " Ducks have been domesticated for thousands of years for their meat, eggs, and feathers.",
    " The hooded merganser is known for its impressive crest of feathers that can be expanded or contracted.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater.",
    " The common teal is one of the smallest duck species and is known for its beautiful green wing patches.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " The lesser scaup is known for its distinctive black head and white body, which can be seen during courtship displays.",
    " Ducks have been studied extensively for their migration patterns and are often used as indicators of environmental changes.",
    " The bufflehead is a small diving duck with a striking black-and-white plumage and iridescent head.",
    " Ducks have a specialized muscle in their legs that allows them to swim efficiently and with great speed.",
    " The common eider is known for its unique nesting behavior, often building nests on rocky cliffs and islands.",
    " Ducks have a specialized structure in their digestive system that allows them to process a wide range of food types.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have been featured in various forms of art and literature, from ancient Egyptian hieroglyphs to modern cartoons.",
    " The northern pintail is known for its elegant and slender neck, which gives it a distinctive appearance.",
    " Ducks are often seen in pairs or small groups, especially during the breeding season.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks use their bills to sift through water and mud to find food, often creating a feeding behavior called dabbling.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill, which make it easy to identify in the wild.",
    " Ducks have a wide range of vocalizations, including quacks, whistles, and grunts, depending on the species and situation.",
    " The red-breasted merganser is a diving duck that is well adapted to catching fish with its sharp bill.",
    " Ducks have a specialized gland near their tail called the uropygial gland, which helps keep their feathers waterproof.",
    " The common teal is known for its vibrant plumage and distinctive call, making it a favorite among birdwatchers.",
    " Ducks are important for maintaining the health of wetland ecosystems by controlling insect and plant populations.",
    " The black scoter is a diving duck with a distinctive black plumage and sharp bill that it uses to catch prey.",
    " Ducks have a unique way of navigating through water, using their webbed feet and streamlined bodies.",
    " The wood duck is notable for its striking plumage and ability to perch in trees.",
    " Ducks often form large flocks during migration and feeding, which can include hundreds or even thousands of individuals.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The mallard is one of the most common and widespread duck species, found in a variety of habitats around the world.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks have a unique way of preening their feathers, using their beaks to clean and arrange them.",
    " The canvasback duck is known for its distinctive head shape and long, slender bill, which are useful for catching fish.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The redhead duck is easily recognizable by its distinctive red head and neck.",
    " Ducks have been featured in various forms of popular media, including books, films, and television shows.",
    " The long-tailed duck is known for its distinctive long tail feathers and striking plumage.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The black-bellied whistling duck is known for its distinctive call and striking black belly.",
    " Ducks often use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The bufflehead is a small diving duck with a striking black-and-white plumage and iridescent head.",
    " Ducks have a specialized muscle in their legs that helps them swim efficiently and with great speed.",
    " The common merganser is known for its serrated bill, which is adapted for catching fish.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " The northern pintail is known for its elegant and slender neck, which gives it a distinctive appearance.",
    " Ducks use a range of vocalizations and body language to communicate with each other, especially during the breeding season.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The wood duck is unique among ducks for its ability to perch in trees thanks to its strong claws and agile feet.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for food.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have been featured in various forms of art and literature throughout history, from ancient Egyptian hieroglyphs to modern cartoons.",
    " The common eider is known for its unique nesting behavior, often building nests on rocky cliffs and islands.",
    " Ducks have a specialized structure in their digestive system that allows them to process a wide range of food types.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks are highly social animals and often form large groups when feeding or migrating.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to filter out small food particles from the water, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive crest of feathers that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The whistling duck gets its name from its distinctive whistling call, which is used for communication between mates and family members.",
    " Ducks have a specialized bill structure called lamellae, which helps them filter out small food particles from the water.",
    " The redhead duck is easily recognizable by its distinctive red head and neck.",
    " Ducks have a unique way of preening their feathers, using their beaks to clean and arrange them.",
    " The long-tailed duck is known for its distinctive long tail feathers and striking plumage.",
    " Ducks have been featured in various cultural celebrations and folklore around the world.",
    " The common merganser is an excellent fisherman, using its serrated bill to catch and hold slippery fish.",
    " Ducks are important for maintaining the health of wetland ecosystems by controlling insect and plant populations.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater.",
    " The green-winged",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The mallard is one of the most common and widespread duck species, found in a variety of habitats around the world.",
    " Ducks use a variety of vocalizations and body language to communicate with each other, especially during the breeding season.",
    " The black-bellied whistling duck is known for its distinctive whistling call and striking black belly.",
    " Ducks have a unique way of navigating through water, using their webbed feet and streamlined bodies.",
    " The wood duck is notable for its striking plumage and ability to perch in trees.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common teal is known for its vibrant plumage and distinctive call.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The common eider is known for its unique nesting behavior, often building nests on rocky cliffs and islands.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a unique way of preening their feathers, using their beaks to clean and arrange them.",
    " The hooded merganser is known for its impressive crest of feathers that can be expanded or contracted.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The whistling duck gets its name from its distinctive whistling call, which is used for communication between mates and family members.",
    " Ducks have a specialized bill structure called lamellae, which helps them filter out small food particles from the water.",
    " The redhead duck is easily recognizable by its distinctive red head and neck.",
    " Ducks have a unique way of navigating through water, using their webbed feet and streamlined bodies.",
    " The wood duck is notable for its striking plumage and ability to perch in trees.",
    " Ducks have been featured in various cultural celebrations and folklore around the world.",
    " The common merganser is an excellent fisherman, using its serrated bill to catch and hold slippery fish.",
    " Ducks are important for maintaining the health of wetland ecosystems by controlling insect and plant populations.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The mallard is one of the most common and widespread duck species, found in a variety of habitats around the world.",
    " Ducks use a variety of vocalizations and body language to communicate with each other, especially during the breeding season.",
    " The black-bellied whistling duck is known for its distinctive whistling call and striking black belly.",
    " Ducks have a unique way of preening their feathers, using their beaks to clean and arrange them.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food,",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers,",
    " Ducks are important for controlling aquatic plant growth by feeding on algae and other vegetation.",
    " Ducks often form monogamous pairs for the breeding season, with both parents participating in raising the young.",
    " The black scoter is a diving duck known for its distinctive black plumage and sharp bill.",
    " Ducks use their bills to sift through water and mud to find food, a behavior known as dabbling.",
    " The mallard is one of the most recognizable duck species due to its distinctive coloring and quacking call.",
    " Ducks have a highly developed sense of hearing, which helps them detect predators and locate mates.",
    " The hooded merganser is known for its impressive feather crest that can be expanded or contracted.",
    " Ducks have been domesticated for thousands of years and are raised for their meat, eggs, and feathers.",
    " The lesser scaup is known for its distinctive black head and white body.",
    " Ducks often form large flocks during migration, which can include hundreds or even thousands of individuals.",
    " The canvasback duck is known for its distinctive sloping head and long, slender bill.",
    " Ducks have a wide range of feeding habits, from dabbling on the surface to diving underwater for prey.",
    " The tufted duck is known for its distinctive crest of feathers on its head, which can be raised or lowered.",
    " Ducks have been featured in various forms of art and literature throughout history.",
    " The green-winged teal is one of the smallest and most colorful ducks found in North America.",
    " Ducks have a specialized gland located near their tail that produces oil to keep their feathers waterproof.",
    " The red-breasted merganser is known for its sharp bill and distinctive red breast.",
    " Ducks use a variety of strategies to find food, including dabbling on the surface, diving underwater, and filtering through mud.",
    " The common eider is known for its soft down feathers, which are highly valued for insulation in cold climates.",
            ];
            function getDailyFact() {
                const today = new Date();
                const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / (1000 * 60 * 60 * 24));
                const factIndex = dayOfYear % facts.length;
                return facts[factIndex];
            }
            document.getElementById('duckFact').innerText = getDailyFact();
// end

